### ISSUE TITLE
Heroku policy

### ISSUE THREAD

**Issue by asciixster** [sbatrow/DarkV2ray-Manager-Bot#1]
"Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by asciixster** [comment]
forked under my "name" and bypass heroku issue

**Comment by sbatrow** [comment]
hey fork this repo and re name deploy link like this   (https://heroku.com/deploy?template=your repo link)
