### ISSUE TITLE
Can't Deploy The App For Heroku

### ISSUE THREAD

**Issue by Niraj-Dilshan** [sbatrow/DarkV2ray-Manager-Bot#2]
![image](https://user-images.githubusercontent.com/61787989/157360826-70dd799f-8f38-4a9b-8b22-742a99185713.png)
Can You Add Replit Deploy Instead Of Heroku Cause There Is No Restrictions There.

**Comment by sbatrow** [comment]
hey can you fork this repo and re name deploy link like this   (https://heroku.com/deploy?template=your repo link)
